### PR TITLE
Changes Summary

### PR DESCRIPTION
**Pull request by premaarya**
1. Added Training Status Enum (for readibility)
2. Added TrainAndGetCompletedStatus
3. Added AddBatchExamples
4. Added BatchExample  Model 
5. Added optional param for DeleteIntentAsync for deleting utterances 
6. Updated Publish Model - as per new response from publish api
7. Added test cases for all the changes

### CODE REVIEW

**Comment by andreluizsecco** [comment]
Hi Prema, thank you for taking your time to help. Some questions about your pull request:
1) Why were .orig files created? Just to keep a history of the originals?
2) Why was the Publish class changed, could it explain the changes based on the LUIS Programmatic API?
3) I still need to analyze the "TrainAndGetCompletionStatusAsync" method. Do not you think 15 minutes is a very high timeout time?

**Comment by premaarya** [comment]
Hello Andre,
1. My bad, I merged the code from original   branch to mine and then pull request.. used the kdiff3 it keeps an .orig file..we can delete that ..as we have all history.
2. There is no update in the API documentation, however, I inspected the json response and it didn't match the one we have and documented ..so updated. 
3. I agree we can reduce the wait time may be 8 mins.. our model with around 80 intents took 5 mins to create train and publish ..if the operation completed before we get the response. We can discuss .. I am returning the response for overall app same data structure as a status of single object in the app..

**Comment by andreluizsecco** [comment]
Great!
Thank you for your contribution. I'll make some changes, such as timeout and some refactorings.

**Review by andreluizsecco — APPROVED** [review]

**Comment by premaarya** [comment]
Great Thanks !

**Comment by andreluizsecco** [comment]
Hey @premaarya, take a look in the implementation refactored of TrainAndGetFinalStatusAsync [(Link)](https://github.com/andreluizsecco/Cognitive-LUIS-Programmatic/blob/dev/Cognitive.LUIS.Programmatic/TrainingService.cs#L47) method. I changed some points such as timeout parameter, etc. If you has any considerations, please comment in this issue: [#7](https://github.com/andreluizsecco/Cognitive-LUIS-Programmatic/issues/7)

**Comment by premaarya** [comment]
Hello  @andreluizsecco  the method is optimized now looks great ! Thank you !

**Comment by andreluizsecco** [comment]
Hello @premaarya, the 1.1.0-preview version is available in [https://www.nuget.org/packages/Cognitive.LUIS.Programmatic/1.1.0-preview](https://www.nuget.org/packages/Cognitive.LUIS.Programmatic/1.1.0-preview).
The final version should be released at end of the month. Feel free to try it. Thanks!

**Pull request merged**
